
#languageCode = 'en-us'
#title = 'Reshmee blog'
#theme = 'ananke'

#[taxonomies]
 # tag = "tag"
  #category = "category"

#[outputs]
 # home = ['HTML', 'RSS']
  #page = ['HTML', 'RSS']  
#


title = "Reshmee Auckloo"
baseURL = 'https://reshmee.netlify.app/'
languageCode = "en-uk"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-KGKC5Z2FEV"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Welcome to my blog post. I am Reshmee Auckloo, a SharePoint Developer from United Kingdom. I am passionate about development and I love to share my knowledge with others. I am also a tech enthusiast and I love to learn new things."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6
  commentoEnable = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/reshmeeauckloo"


