baseURL = 'https://famous-cajeta-4dad83.netlify.app/'
languageCode = 'en-us'
title = 'm365 blog'
theme = 'ananke'

[taxonomies]
  tag = "tag"
  category = "category"

[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML', 'RSS']  