baseURL = 'https://reshmee.netlify.app/'
languageCode = 'en-us'
title = 'Reshmee blog'
theme = 'ananke'

[taxonomies]
  tag = "tag"
  category = "category"

[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML', 'RSS']  