# netlify.toml, ref https://davidrothera.me/posts/getting-started-with-hugo/

[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
NODE_ENV = "production"
GO_VERSION = "1.19.4"
TZ = "Europe/Dublin"    # Set to preferred timezone

[context.production.environment]
HUGO_VERSION = "0.109.0"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.109.0"
